export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_FOODS_SUCCESS = 'LOAD_FOODS_SUCCESS';
export const CREATE_FOOD_SUCCESS = 'CREATE_FOOD_SUCCESS';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';